### ISSUE TITLE
Задачи для фронта

### ISSUE THREAD

**Issue by NightOfNights** [Pocindle/Pocindle#3]
1. Авторизация в приложение через Pocket #1 
2. Отображение статей пользователя с Pocket #2
3. Отправка по почте выбранной статьи на электронную книгу

**Comment by prekel** [comment]
3: 
 - Пользователь пишет емейл-адрес своего kindle, который получает на сайте амазона
 - Пользователю будет выдан адрес с которого будут идти сообщения, он должен будет его на сайте амазона добавить в белый список
