### ISSUE TITLE
Пояснительная записка

### ISSUE THREAD

**Issue by prekel** [Pocindle/Pocindle#50]
Используя СТО 4.2–07–2014, подготовьте следующие разделы Пояснительной записки по вашему командному курсовому проекту:

Введение - объем 1-2 страницы
1. Анализ предметной области - объем до 10 страниц.

Пояснительная записка оформляется одна на команду.

**Comment by prekel** [comment]
https://docs.google.com/document/d/1bmfC8JMrNUhM9HouRA54an98dZwbdzVItSEGHOlnLVk/edit?usp=sharing

**Comment by NightOfNights** [comment]
https://docs.google.com/document/d/1_ZnaLQHZhTsZ4kOQcgIE9I03CN9X1r_q/edit

**Comment by NightOfNights** [comment]
поменял ссылку, так как залил свой со второго курса с форматированием

**Comment by NightOfNights** [comment]
Залил, жду проверки

**Comment by NightOfNights** [comment]
Используя СТО 4.2–07–2014, подготовьте второй раздел Пояснительной записки по Вашему командному курсовому проекту:

2. Управление проектом (персонал, риски, коммуникации, заинтересованные стороны).

Пояснительная записка оформляется одна на команду.

**Comment by NightOfNights** [comment]
Также залил второй раздел

**Comment by NightOfNights** [comment]
Замечания:

- [x] 1. Поменять название проекта + инициалы добавить
- [x] 2. Персонал и коммуникациИ
- [ ] 3. Светлая тема для скриншотов
- [x] 4. Риски пересчитать по формуле
- [x] 5. Стратегии к заинтересованным сторонам
- [x] 6. Ссылки не должны быть на вики

**Comment by NightOfNights** [comment]
Доделать к выходным

**Comment by prekel** [comment]
![image](https://user-images.githubusercontent.com/19646569/119480482-eecd6f80-bd7b-11eb-97f1-af81a8519c85.png)
